apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-enbx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-enbx@sha256:7f59a04e2c00633ff00658745bc4c290afef385bf82d491f02343628bac4261f
        name: my-nodejs
        resources: {}
status: {}
